
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebService2Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService2Soap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld2", action = "http://tempuri.org/HelloWorld2")
    @WebResult(name = "HelloWorld2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld2")
    @ResponseWrapper(localName = "HelloWorld2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld2Response")
    public String helloWorld2();

    /**
     * 
     * @param senderId
     * @param routeId
     * @param receivedId
     * @param name
     * @param description
     * @param tracked
     * @param receiverCity
     * @param senderCity
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/insertPackage")
    @WebResult(name = "insertPackageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "insertPackage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertPackage")
    @ResponseWrapper(localName = "insertPackageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertPackageResponse")
    public String insertPackage(
        @WebParam(name = "senderId", targetNamespace = "http://tempuri.org/")
        int senderId,
        @WebParam(name = "receivedId", targetNamespace = "http://tempuri.org/")
        int receivedId,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        String description,
        @WebParam(name = "senderCity", targetNamespace = "http://tempuri.org/")
        String senderCity,
        @WebParam(name = "receiverCity", targetNamespace = "http://tempuri.org/")
        String receiverCity,
        @WebParam(name = "tracked", targetNamespace = "http://tempuri.org/")
        boolean tracked,
        @WebParam(name = "routeId", targetNamespace = "http://tempuri.org/")
        int routeId);

    /**
     * 
     * @param packageId
     * @param tracked
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updatePackage")
    @WebResult(name = "updatePackageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updatePackage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdatePackage")
    @ResponseWrapper(localName = "updatePackageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdatePackageResponse")
    public String updatePackage(
        @WebParam(name = "packageId", targetNamespace = "http://tempuri.org/")
        int packageId,
        @WebParam(name = "tracked", targetNamespace = "http://tempuri.org/")
        boolean tracked);

    /**
     * 
     * @param packageId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/deletePackage")
    @WebResult(name = "deletePackageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "deletePackage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeletePackage")
    @ResponseWrapper(localName = "deletePackageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeletePackageResponse")
    public String deletePackage(
        @WebParam(name = "packageId", targetNamespace = "http://tempuri.org/")
        int packageId);

    /**
     * 
     * @param city
     * @param id
     * @param time
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/addRouteToPackage")
    @WebResult(name = "addRouteToPackageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "addRouteToPackage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRouteToPackage")
    @ResponseWrapper(localName = "addRouteToPackageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRouteToPackageResponse")
    public String addRouteToPackage(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id,
        @WebParam(name = "city", targetNamespace = "http://tempuri.org/")
        String city,
        @WebParam(name = "time", targetNamespace = "http://tempuri.org/")
        long time);

}
