package utcluj.ac.ro.ws2;


import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebService2", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:50642/WebSite1/WebService2.asmx?wsdl")
public class WebService2
    extends Service
{

    private final static URL WEBSERVICE2_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICE2_EXCEPTION;
    private final static QName WEBSERVICE2_QNAME = new QName("http://tempuri.org/", "WebService2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:50642/WebSite1/WebService2.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICE2_WSDL_LOCATION = url;
        WEBSERVICE2_EXCEPTION = e;
    }

    public WebService2() {
        super(__getWsdlLocation(), WEBSERVICE2_QNAME);
    }

    public WebService2(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICE2_QNAME, features);
    }

    public WebService2(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICE2_QNAME);
    }

    public WebService2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICE2_QNAME, features);
    }

    public WebService2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebService2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebService2Soap
     */
    @WebEndpoint(name = "WebService2Soap")
    public WebService2Soap getWebService2Soap() {
        return super.getPort(new QName("http://tempuri.org/", "WebService2Soap"), WebService2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService2Soap
     */
    @WebEndpoint(name = "WebService2Soap")
    public WebService2Soap getWebService2Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WebService2Soap"), WebService2Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICE2_EXCEPTION!= null) {
            throw WEBSERVICE2_EXCEPTION;
        }
        return WEBSERVICE2_WSDL_LOCATION;
    }

}
