package utcluj.ac.ro.ws2;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebService2Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService2Soap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld2", action = "http://tempuri.org/HelloWorld2")
    @WebResult(name = "HelloWorld2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld2")
    @ResponseWrapper(localName = "HelloWorld2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld2Response")
    public String helloWorld2();

}
