
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS1", targetNamespace = "http://ws/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WS1 {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ws.PackageToSend
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/WS1/getClientPackageRequest", output = "http://ws/WS1/getClientPackageResponse")
    public PackageToSend getClientPackage(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/WS1/isAdminAuthentificationOKRequest", output = "http://ws/WS1/isAdminAuthentificationOKResponse")
    public boolean isAdminAuthentificationOK(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/WS1/isClientAuthentificationOKRequest", output = "http://ws/WS1/isClientAuthentificationOKResponse")
    public boolean isClientAuthentificationOK(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/WS1/registerNewClientRequest", output = "http://ws/WS1/registerNewClientResponse")
    public String registerNewClient(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.ResponseArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/WS1/getClientPackagesRequest", output = "http://ws/WS1/getClientPackagesResponse")
    public ResponseArrayList getClientPackages(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
