
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS1ImplService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/sdnext/ws1?wsdl")
public class WS1ImplService
    extends Service
{

    private final static URL WS1IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WS1IMPLSERVICE_EXCEPTION;
    private final static QName WS1IMPLSERVICE_QNAME = new QName("http://ws/", "WS1ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sdnext/ws1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WS1IMPLSERVICE_WSDL_LOCATION = url;
        WS1IMPLSERVICE_EXCEPTION = e;
    }

    public WS1ImplService() {
        super(__getWsdlLocation(), WS1IMPLSERVICE_QNAME);
    }

    public WS1ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WS1IMPLSERVICE_QNAME, features);
    }

    public WS1ImplService(URL wsdlLocation) {
        super(wsdlLocation, WS1IMPLSERVICE_QNAME);
    }

    public WS1ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WS1IMPLSERVICE_QNAME, features);
    }

    public WS1ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WS1ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WS1
     */
    @WebEndpoint(name = "WS1ImplPort")
    public WS1 getWS1ImplPort() {
        return super.getPort(new QName("http://ws/", "WS1ImplPort"), WS1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WS1
     */
    @WebEndpoint(name = "WS1ImplPort")
    public WS1 getWS1ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "WS1ImplPort"), WS1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WS1IMPLSERVICE_EXCEPTION!= null) {
            throw WS1IMPLSERVICE_EXCEPTION;
        }
        return WS1IMPLSERVICE_WSDL_LOCATION;
    }

}
